manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
      
  projects:
    - name: zmk
      remote: infused-kim
      revision: 47bd2cc46de99f722e57e27e3a28d7ea367a880a  # Known working
      import: app/west.yml
    
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: infused-kim
      revision: main

  self:
    path: config
